Feature/customerloyalty credential
credential-handler/vc-examples pull request #22
Opened 2023-06-28 18:06 UTC by ottonomy

Prerequisite: Merge PR #21 to add the context to the repository.

Adds a `CustomerLoyaltyCredential` example to the repository. 

> Retail establishments often offer a [loyalty program](https://en.wikipedia.org/wiki/Loyalty_program) to encourage customers to make repeat purchases. A loyalty program typically involves a customer signing up for a program and receiving a loyalty card. The customer presents the loyalty card at the point of sale to receive discounts or other benefits. The loyalty card is typically a plastic card with a barcode or magnetic stripe that can be scanned at the point of sale. The loyalty card is associated with a customer account identifier, so that the store can track the customer's purchases and apply rewards.
>
> A `CustomerLoyaltyCredential` is a digital representation of a loyalty card. It can be presented by a customer to a retailer to receive discounts or other benefits. The credential asserts the customer account identifier and optionally which location the card is associated with. The credential is signed and verified by the retailer.

2023-06-29 15:30 UTC, dlongley requested changes

2023-06-30 02:49 UTC, davidlehn commented
@ottonomy:
- The PR base commit should be adjusted to the branch for the #21 PR.
- There are context comments here that should likely be in #21, so I didn't change the base in case it would drop those.

2023-09-13 16:58 UTC, ottonomy commented on contexts/customer-loyalty/v1.json
> +    "@version": 1.1,
Resolved in #21

2023-09-13 21:55 UTC, ottonomy commented
Status now after I came back from vacation:
* This PR is in draft state and is not planned to be reviewed or merged until after #21 is merged, at which point this will switch to ready-for-review, which is why the commit that adds context from that branch is also present in this branch. It is a prerequisite to the commits here making any sense, they are not independent changes. Confirmed this strategy via meeting earlier today. 
* Context comments left in this PR have been resolved on the branch for #21, which is ready for review.
* After #21 is merged, this will be rebased to resolve changes to `CHANGELOG.md`.

2023-09-21 13:46 UTC, dlongley approved these changes
Thanks!

2023-09-22 00:34 UTC, davidlehn commented on credentials/customer-loyalty/credential.json
> +    "image": "https://playground.chapi.io/examples/retail-coupon/logo.png",
Use vcplayground.org:
```suggestion
    "image": "https://vcplayground.org/examples/retail-coupon/logo.png",
```
I'd consider copying the logo image over to customer-loyalty so the example is self contained and resistant to changes in the retail-coupon example.

2023-09-22 00:34 UTC, davidlehn commented on credentials/customer-loyalty/credential.json
> +  "image": "https://playground.chapi.io/examples/customer-loyalty/image.png",
Use vcplayground.org:
```suggestion
  "image": "https://vcplayground.org/examples/customer-loyalty/image.png",
```

2023-10-23 17:19 UTC, BigBlueHat commented
@ottonomy this looks nearly done. Could you consolidate the images and update the VC Playground URLs?

Thanks!

2023-10-23 17:32 UTC, gannan08 commented
@BigBlueHat I will takeover this PR.

2023-10-30 15:55 UTC, merged