Update dl
credential-handler/vc-examples pull request #46
Opened 2024-06-17 21:25 UTC by jameseaster

#### _Resolves - add more detail & contexts to dl_

---

### What kind of change does this PR introduce?

- DL credential update.

<br/>

### What is the current behavior?

- More information needed for DL example.

<br/>

### What is the new behavior?

- More credential subject values, types, and context are added from the [W3C verifiable DL vocabulary example](https://w3c-ccg.github.io/vdl-vocab/#example-a-iso18013-5-mdl-expressed-as-a-w3c-verifiable-credential)

<br/>

### Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

<br/>

### How has this been tested?

- Credential has been issued and viewed locally.

<br/>

### Screenshots: n/a

2024-06-24 18:53 UTC, BigBlueHat commented on credentials/utopia-dl/credential.json
> +      "portrait": "https://vcplayground.org/examples/utopia-dl/dl-male-portrait.png",
```suggestion
      "image": "https://vcplayground.org/examples/utopia-dl/dl-male-portrait.png",
```

2024-06-24 21:12 UTC, BigBlueHat requested changes
@jameseaster can you add a `resident_address` field to this credential? Annoyingly it's just an undifferentiated string in an mDL...

Here's the address to use:
123 Main Street
Anyville, UTO F87P2

2024-06-27 16:04 UTC, jameseaster commented
@BigBlueHat 
Overall, huge improvement on load time! Looks like a few text issues with the dates,  looking killer as always though!

For reference:

> SVG with values
>
> <img alt="svg" width="400px" src="https://github.com/credential-handler/vc-examples/assets/56396286/09547167-1ae9-468c-a265-da488a423907" />

2024-07-01 15:48 UTC, BigBlueHat commented
@jameseaster give this another test if you would. I've inlined the https://fonts.google.com/specimen/Manrope font into the SVG (via CSS).

2024-07-01 19:51 UTC, BigBlueHat commented
Here's what things should look like when rendered:
![image](https://github.com/credential-handler/vc-examples/assets/43209/42efdf49-9ad1-4817-aefd-ca15eac07147)

Remaining issues include:
[ ] date formatting (see `exp`)
[ ] missing values (notably `hgt` will need additional parsing/formatting/conversion)
[ ] mapping the `sex` integer from the upstream spec to a meaningful value

2024-07-02 18:19 UTC, BigBlueHat commented
Latest and geatest.
![image](https://github.com/credential-handler/vc-examples/assets/43209/fb6c86a4-886d-4895-a83f-4929d1462e04)

Font issues all fixed. Date format "cheated" (for now) by only storying the date (sans time) in the credential info. Other missing data was added. The `sex` value is still not mapped to anything meaningful...as we need to discuss how we want to do that.

2024-07-03 19:51 UTC, BigBlueHat approved these changes
@jameseaster this probably needs your review...even though GitHub doesn't realize PRs might have multiple authors who need to review each others code...yet(?).

2024-07-03 22:12 UTC, jameseaster commented
@BigBlueHat The DL is unable to be issued in the playground. I'm receiving this error:
```
Unable to generate/issue credential: Unable to issue credential on selected backend: "expirationDate" must be a valid date: 2030-04-19
```

2024-07-04 02:28 UTC, davidlehn commented
4MB json, 2.8MB svg, 168KB image.  Any chance for optimization here?

2024-07-05 15:41 UTC, jameseaster commented
> 4MB json, 2.8MB svg, 168KB image. Any chance for optimization here?

@davidlehn @BigBlueHat @dlongley 
Could be helpful to link to an image property with a url, rather than using a massive base64 string. I know there are some security questions here, but seems like a quick win to help minimize the json for the credential.

2024-07-08 15:54 UTC, BigBlueHat commented
> This seems like a new error, and I can see the value in the credential `"expirationDate": "2030-04-19T12:00:00-06:00"`

It's because I reduced the `expirationDate` value down to `2030-04-19` so it looks good in the design... I don't understand why that's not being treated as a valid date...other than we've gone a bit farther than ISO 8601 dates in our requirements. @dlongley thoughts?

2024-07-08 15:56 UTC, dlongley commented
@BigBlueHat, yeah, IIRC, it needs to be a datetime in the spec, not just a date. At least, I think that's a requirement for `validUntil` in VC 2.0. Ultimately, we want the render method to be able to handle this -- so we need to find a solution for that.

2024-07-08 16:15 UTC, BigBlueHat commented
> @BigBlueHat, yeah, IIRC, it needs to be a datetime in the spec, not just a date. At least, I think that's a requirement for `validUntil` in VC 2.0. Ultimately, we want the render method to be able to handle this -- so we need to find a solution for that.

Yeah, `validUntil` is more than an ISO 8601, apparently. Specifically, it's https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp

2024-07-08 19:57 UTC, BigBlueHat commented
@jameseaster could you give this another try on your side?

2024-07-08 22:31 UTC, jameseaster commented
@BigBlueHat It is unable to render the displays b/c of the change to raw svg

2024-07-09 00:40 UTC, davidlehn commented
You can lint the JSON with the json-ld playground or jsonld-cli.  It thinks the inline svg is a relative URL.  It looks like it needs to be URL encoded (which will increase the size).  Consider first running source through svgo to optimize more bytes out.

2024-07-09 17:00 UTC, jameseaster commented
Rendered locally with the compressed svg stored in `template` - LGTM

Thanks @BigBlueHat!

2024-07-11 13:01 UTC, merged